@echo off
echo Starting Grok-Notes Servers...

:: Backend Setup and Start
cd backend
echo Checking for virtual environment...
if not exist .venv (
    echo Creating virtual environment...
    python -m venv .venv
    echo Activating virtual environment...
    call .venv\Scripts\activate.bat
    echo Installing dependencies...
    pip install -r requirements.txt
) else (
    echo Virtual environment found. Activating...
    call .venv\Scripts\activate.bat
)

echo Starting Backend Server...
start cmd /k "uvicorn main:app --reload"

:: Frontend Setup and Start
cd ..\frontend
echo Checking for node modules...
if not exist node_modules (
    echo Installing frontend dependencies...
    npm install
)

echo Starting Frontend Server...
start cmd /k "npm run dev"

echo Servers are starting in separate windows...
cd ..
